-- Starter chord catalog, ported from the DB object in formatador-cifra.html.
-- Runs exactly once (migration tracking in schema_migrations prevents re-application),
-- so it seeds a fresh install without ever fighting the owner's later edits.

INSERT INTO chords (name, frets, created_at, updated_at) VALUES
  ('C', 'x 3 2 0 1 0', datetime('now'), datetime('now')),
  ('D', 'x x 0 2 3 2', datetime('now'), datetime('now')),
  ('E', '0 2 2 1 0 0', datetime('now'), datetime('now')),
  ('F', '1 3 3 2 1 1', datetime('now'), datetime('now')),
  ('G', '3 2 0 0 0 3', datetime('now'), datetime('now')),
  ('A', 'x 0 2 2 2 0', datetime('now'), datetime('now')),
  ('B', 'x 2 4 4 4 2', datetime('now'), datetime('now')),
  ('Cm', 'x 3 5 5 4 3', datetime('now'), datetime('now')),
  ('Dm', 'x x 0 2 3 1', datetime('now'), datetime('now')),
  ('Em', '0 2 2 0 0 0', datetime('now'), datetime('now')),
  ('Fm', '1 3 3 1 1 1', datetime('now'), datetime('now')),
  ('Gm', '3 5 5 3 3 3', datetime('now'), datetime('now')),
  ('Am', 'x 0 2 2 1 0', datetime('now'), datetime('now')),
  ('Bm', 'x 2 4 4 3 2', datetime('now'), datetime('now')),
  ('C7', 'x 3 2 3 1 0', datetime('now'), datetime('now')),
  ('D7', 'x x 0 2 1 2', datetime('now'), datetime('now')),
  ('E7', '0 2 0 1 0 0', datetime('now'), datetime('now')),
  ('G7', '3 2 0 0 0 1', datetime('now'), datetime('now')),
  ('A7', 'x 0 2 0 2 0', datetime('now'), datetime('now')),
  ('B7', 'x 2 1 2 0 2', datetime('now'), datetime('now')),
  ('Cmaj7', 'x 3 2 0 0 0', datetime('now'), datetime('now')),
  ('Dmaj7', 'x x 0 2 2 2', datetime('now'), datetime('now')),
  ('Fmaj7', 'x x 3 2 1 0', datetime('now'), datetime('now')),
  ('Gmaj7', '3 2 0 0 0 2', datetime('now'), datetime('now')),
  ('Amaj7', 'x 0 2 1 2 0', datetime('now'), datetime('now')),
  ('Em7', '0 2 0 0 0 0', datetime('now'), datetime('now')),
  ('Am7', 'x 0 2 0 1 0', datetime('now'), datetime('now')),
  ('Dm7', 'x x 0 2 1 1', datetime('now'), datetime('now')),
  ('Bm7', 'x 2 0 2 0 2', datetime('now'), datetime('now')),
  ('F#m', '2 4 4 2 2 2', datetime('now'), datetime('now')),
  ('C#m', 'x 4 6 6 5 4', datetime('now'), datetime('now')),
  ('C9', 'x 3 2 0 3 3', datetime('now'), datetime('now')),
  ('D9', 'x x 0 2 3 0', datetime('now'), datetime('now')),
  ('G9', '3 x 0 2 0 1', datetime('now'), datetime('now')),
  ('A9', 'x 0 2 2 0 0', datetime('now'), datetime('now')),
  ('E9', '0 2 2 1 0 2', datetime('now'), datetime('now')),
  ('C4', 'x 3 3 0 1 1', datetime('now'), datetime('now')),
  ('D4', 'x x 0 2 3 3', datetime('now'), datetime('now')),
  ('E4', '0 2 2 2 0 0', datetime('now'), datetime('now')),
  ('G4', '3 3 0 0 1 3', datetime('now'), datetime('now')),
  ('A4', 'x 0 2 2 3 0', datetime('now'), datetime('now')),
  ('Csus4', 'x 3 3 0 1 1', datetime('now'), datetime('now')),
  ('Dsus4', 'x x 0 2 3 3', datetime('now'), datetime('now')),
  ('Esus4', '0 2 2 2 0 0', datetime('now'), datetime('now')),
  ('Gsus4', '3 3 0 0 1 3', datetime('now'), datetime('now')),
  ('Asus4', 'x 0 2 2 3 0', datetime('now'), datetime('now')),
  ('C/G', '3 3 2 0 1 0', datetime('now'), datetime('now')),
  ('D/F#', '2 0 0 2 3 2', datetime('now'), datetime('now')),
  ('G/B', 'x 2 0 0 0 3', datetime('now'), datetime('now')),
  ('F/A', 'x 0 3 2 1 1', datetime('now'), datetime('now')),
  ('Am/G', '3 0 2 2 1 0', datetime('now'), datetime('now')),
  ('Em9', '0 2 2 0 0 2', datetime('now'), datetime('now')),
  ('Cadd9', 'x 3 2 0 3 0', datetime('now'), datetime('now'));
